from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select


driver_service = Service("C:\\Users\\91638\\PycharmProjects\\OrangeHRM\\Drivers\\chromedriver.exe")
driver = webdriver.Chrome(service=driver_service)
driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
driver.maximize_window()
print(driver.title)
driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
time.sleep(3)
driver.find_element(By.NAME, "username").send_keys("Admin")
driver.find_element(By.NAME, "password").send_keys("admin123")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button").click()
time.sleep(3)

# TC_PIM_01
list_of_menuitems = []
menu_display = driver.find_elements(By.XPATH, "//li[@class='oxd-main-menu-item-wrapper']")
for i in menu_display:
            list_of_menuitems.append(i.text)
            print(list_of_menuitems)
search_button = driver.find_element(By.XPATH, "//input[@placeholder='Search']")
for a in list_of_menuitems:
            search_button.send_keys(a.upper())
            time.sleep(1)
            search_button.send_keys(Keys.CONTROL, 'a')
            search_button.send_keys(Keys.BACKSPACE)
for b in list_of_menuitems:
            search_button.send_keys(b.lower())
            time.sleep(1)
            search_button.send_keys(Keys.CONTROL, 'a')
            search_button.send_keys(Keys.BACKSPACE)
            time.sleep(5)

# TC_PIM_02
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a").click()
time.sleep(2)
driver.implicitly_wait(3)
User_Role = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(User_Role)
drp.select_by_visible_text("Admin")
driver.implicitly_wait(2)
Status0 = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Status0)
drp.select_by_visible_text("Enabled")
driver.implicitly_wait(5)
User_Role = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(User_Role)
drp.select_by_visible_text("ESS")
driver.implicitly_wait(2)
Status0 = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Status0)
drp.select_by_visible_text("Disabled")
time.sleep(5)

# TC_PIM_03
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[1]/header/div[2]/nav/ul/li[3]/a").click()
time.sleep(3)
driver.find_element(By.NAME, "firstName").send_keys("Sathiyaseelan")
driver.find_element(By.NAME, "lastName").send_keys("K")
driver.implicitly_wait(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[2]/div/label/span").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[1]/div/div[2]/input").send_keys("Sathiyaseelan")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/input").send_keys("Sathiya@123")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[2]/div/div[2]/input").send_keys("Sathiya@123")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div[1]/div[2]/div/label").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]").click()

# TC_PIM_04
time.sleep(5)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[2]").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[3]/a").click()
time.sleep(2)
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[4]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[5]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[6]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[7]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[8]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[9]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[10]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[11]/a").click()

# TC_PIM_05
driver.implicitly_wait(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input").send_keys("Sathiya")
driver.implicitly_wait(3)
driver.execute_script("window.scrollBy(0,500)")
time.sleep(3)
Nationality = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Nationality)
drp.select_by_visible_text("Indian")
driver.implicitly_wait(3)
Marital_Status = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Marital_Status)
drp.select_by_visible_text("Single")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/label").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[1]/div/div[2]/div/div/input").clear()
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[1]/div/div[2]/div/div/input").send_keys("2002-05-09")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button").click()
driver.implicitly_wait(5)


# TC_PIM_06
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[2]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("sathiya")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/input").send_keys("Tamilnadu")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input").send_keys("123456")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/input").send_keys("Tamilnadu")
driver.implicitly_wait(3)
Country = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Country)
drp.select_by_visible_text("India")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input").send_keys("1234567890")
driver.implicitly_wait(2)
driver.execute_script("window.scrollBy(0,500)")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/input").send_keys("abcd@gamil.com")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button").click()
time.sleep(5)

# TC_PIM_07
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[3]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button").click()
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("sathiya")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input").send_keys("Other")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input").send_keys("1234567890")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]").click()
time.sleep(5)

# TC_PIM_08
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[4]/a").click()
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("Sathiyaseelan")
driver.implicitly_wait(3)
Relationship = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Relationship)
drp.select_by_visible_text("Other")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").clear()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div/div/div[2]/div/div/input").send_keys("2002-05-09")
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]").click()
time.sleep(5)

# TC_PIM_09
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[6]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/input").clear()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/input").send_keys("2022-05-09")
driver.implicitly_wait(3)
Job_Title = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Job_Title)
drp.select_by_visible_text("QA Engineer")
time.sleep(2)
driver.find_element(By.CLASS_NAME, "oxd-text oxd-text--p input-container-filename").send_keys("Software Tester")
driver.implicitly_wait(3)
Job_Category = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Job_Category)
drp.select_by_visible_text("Professionals")
driver.implicitly_wait(3)
Sub_Unit = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Sub_Unit)
drp.select_by_visible_text("Quality Assurance")
driver.implicitly_wait(3)
Employment_Status = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Employment_Status)
drp.select_by_visible_text("Full-Time Permanent")
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/label/span").click()
driver.implicitly_wait(3)
driver.switch_to.frame(0)
driver.find_element(By.XPATH, "//li[@class='oxd-file-input-div']").send_keys("C://Users/91638/PycharmProjects/OrangeHRM/Thinking.jpg")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button").click()
time.sleep(5)

# TC_POM_10
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[1]/div/div[2]/div/div/input").clear()
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[1]/div/div[2]/div/div/input").send_keys("2022-03-05")
time.sleep(2)
driver.implicitly_wait(3)
Sub_Unit = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Sub_Unit)
drp.select_by_visible_text("Other")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[4]/button[2]").click()
time.sleep(5)

# TC_POM_11
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[6]/a").click()
time.sleep(2)
driver.execute_script("window.scrollBy(0,500)")
time.sleep(5)

# TC_POM_12
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[7]/a").click()
time.sleep(2)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input").send_keys("abacd")
driver.implicitly_wait(3)
Pay_Grade = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Pay_Grade)
drp.select_by_visible_text("Grade 1")
driver.implicitly_wait(3)
Pay_Frequency = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Pay_Frequency)
drp.select_by_visible_text("Monthly")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input").send_keys("123456")
driver.implicitly_wait(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/label/span").click()
driver.implicitly_wait(3)
driver.execute_script("window.scrollBy(0,500)")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[1]/div[1]/div/div[2]/input").send_keys("1234567890")
driver.implicitly_wait(3)
Pay_Frequency = driver.find_element(By.XPATH, "//li[@class='oxd-select-text oxd-select-text--active']")
drp = Select(Pay_Frequency)
drp.select_by_visible_text("Savings")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[2]/div[1]/div/div[2]/input").send_keys("123456")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[2]/div[2]/div/div[2]/input").send_keys("123456")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button[2]").click()
time.sleep(5)

# TC_POM_13
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[1]/div[2]/div[8]/a").click()
time.sleep(2)
driver.implicitly_wait(3)
State = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(State)
drp.select_by_visible_text("Indiana")
driver.implicitly_wait(3)
Status2 = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Status2)
drp.select_by_visible_text("Single")
driver.implicitly_wait(3)
Unemployment_State = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Unemployment_State)
drp.select_by_visible_text("Indiana")
driver.implicitly_wait(3)
Work_State = driver.find_element(By.XPATH, "//li[@class='oxd-select-text-input']")
drp = Select(Work_State)
drp.select_by_visible_text("Indiana")
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button").click()
driver.implicitly_wait(3)
driver.execute_script("window.scrollBy(0,500)")
time.sleep(2)
driver.find_element("//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div/button").click()
time.sleep(2)
driver.implicitly_wait(3)
driver.switch_to.frame(0)
driver.find_element(By.XPATH, "//li[@class='oxd-file-input-div']").send_keys("C://Users/91638/PycharmProjects/OrangeHRM/Thinking.jpg")
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='app']/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[3]/button[2]").click()
time.sleep(5)
driver.close()